import type { Migration } from '@template/shared';

/**
 * Versioned migrations of the Auth database.
 *
 * Versions are immutable once released: a fresh database is built from version 1 upwards and an
 * existing one only receives what it is missing. Changing a released statement is an error — add a
 * new version instead.
 *
 * The template starts at one, which is the schema a new project inherits rather than a record of
 * how it was arrived at.
 */
export const migrations: readonly Migration[] = [
  {
    version: 1,
    name: 'identities-sessions-tokens-audit',
    sql: `
      CREATE TABLE identities (
        id                 uuid PRIMARY KEY,
        -- Registration order, used to determine the very first user deterministically.
        sequence           bigint GENERATED BY DEFAULT AS IDENTITY,
        email              text NOT NULL UNIQUE,
        password_hash      text NOT NULL,
        email_verified_at  timestamptz,
        blocked_at         timestamptz,
        last_login_at      timestamptz,
        created_at         timestamptz NOT NULL DEFAULT now(),
        updated_at         timestamptz NOT NULL DEFAULT now()
      );

      CREATE UNIQUE INDEX identities_sequence_idx ON identities (sequence);
      CREATE INDEX identities_email_lower_idx ON identities (lower(email));

      CREATE TABLE sessions (
        id           uuid PRIMARY KEY,
        identity_id  uuid NOT NULL REFERENCES identities (id) ON DELETE CASCADE,
        -- Only the hash of the session token is stored; the token itself lives in the cookie.
        token_hash   text NOT NULL UNIQUE,
        user_agent   text,
        created_at   timestamptz NOT NULL DEFAULT now(),
        last_seen_at timestamptz NOT NULL DEFAULT now(),
        expires_at   timestamptz NOT NULL,
        revoked_at   timestamptz
      );

      CREATE INDEX sessions_identity_idx ON sessions (identity_id);

      CREATE TABLE auth_tokens (
        id           uuid PRIMARY KEY,
        identity_id  uuid NOT NULL REFERENCES identities (id) ON DELETE CASCADE,
        purpose      text NOT NULL
                     CHECK (purpose IN ('email-verification', 'password-reset', 'email-change')),
        -- Secret tokens are stored hashed only; nobody, including an administrator, can read them.
        token_hash   text NOT NULL UNIQUE,
        payload      jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at   timestamptz NOT NULL DEFAULT now(),
        expires_at   timestamptz NOT NULL,
        used_at      timestamptz
      );

      CREATE INDEX auth_tokens_identity_purpose_idx ON auth_tokens (identity_id, purpose);

      CREATE TABLE auth_audit (
        id            uuid PRIMARY KEY,
        identity_id   uuid REFERENCES identities (id) ON DELETE SET NULL,
        action        text NOT NULL,
        actor_user_id uuid,
        actor_role    text,
        details       jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at    timestamptz NOT NULL DEFAULT now()
      );

      CREATE INDEX auth_audit_created_idx ON auth_audit (created_at DESC);
    `,
  },
];
